title: Interactive Course Grading
description: A simplified, integrated LMS for the IT Product Dev course, designed to streamline individual and group grade management.
theme: just-the-docs

url: https://iu-mymini.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template